### ISSUE TITLE
Godot Discord Pocket embed Discussion.

### ISSUE THREAD

**Issue by TwistedTwigleg** [TwistedTwigleg/vanilla-bootstrap#10]
Here is the link to the code used for to embed Discord using the Pockets plugin in Vanilla: [https://gist.github.com/TwistedTwigleg/697892da0dfab96da88cf0519fce281f](https://gist.github.com/TwistedTwigleg/697892da0dfab96da88cf0519fce281f)

Let me know what you think and leave feedback regarding the W.I.P Discord embed here.

I figure we'll close this issue once we're happy with how the Discord plugin is integrated. After that, I suppose we'll make new issues as we find problems/enhancements.

**Comment by Megalomaniak** [comment]
Might be worth keeping it open since it points to the gist. This way we both have easy access to it again if something should happen and a "backup" be needed.

**Comment by TwistedTwigleg** [comment]
That's true, I didn't think about that. In that case, I agree that it would probably be best to keep this issue open.

**Comment by TwistedTwigleg** [comment]
When changing the side panels so they are collapsible, it appears that caused issues with the Discord pocket embed. I didn't realize this because I didn't have the Discord embed pocket on my localhost server.

I fixed this by making a new pocket called `Discord Embed Pocket` that works for both mobile and desktop (using media queries), editing the `default.master.tpl` file to include `{pocket name="Discord Embed Pocket"}` by the side panel, and then setting the location of the new pocket to `Custom` in Vanilla. Now the Discord embed acts just like it used to prior to the change.

I updated the GitHub gist with the new pocket code and disabled the old pockets, since they are no longer working.

**Comment by Megalomaniak** [comment]
Yes, a custom pocket for it is probably the best solution anyways.

**Comment by Megalomaniak** [comment]
I'm noticing that the discord isn't expanding anymore at all. By design? If so, I think for PC browsers it might be better to have it default to expanded then..?

**Comment by TwistedTwigleg** [comment]
> I'm noticing that the discord isn't expanding anymore at all. By design? If so, I think for PC browsers it might be better to have it default to expanded then..?

It should expand when not on mobile, and on mobile it should be fully expanded, just like the two separate pocket snippets we were using before.

I tested on Firefox, and it expands when the cursor is over it. However, on Microsoft Edge it does not. So yeah, this is a bug. My hunch is that some browsers don't send the `hover` event or something. I dunno, I suppose we'll have to look into it.

**Comment by Megalomaniak** [comment]
I am using waterfox on my end, also have opera installed for testing some edge cases.

**Comment by Megalomaniak** [comment]
Right, so:
https://caniuse.com/#feat=css-media-interaction

Indicates that firefox added support in version 64. Since I use waterfox which is based off of 56 it's no wonder the media-query hover selector is not working for me. Considering that I'm not a discord user myself it's not a problem for me, so for my part I'm fine considering this issue a won't-fix/no issue.

Once the new theme goes live we'll see if there are any users bringing it up. If so we can see about finding an alternative solution perhaps.

**Comment by TwistedTwigleg** [comment]
Works for me.

I'm wondering if we might want to move the discord embed to a plugin anyway, since it adds a fair bit of extra loading time. Personally I don't use Discord myself, so I'd be okay with shaving off the extra loading time by making it configurable on a per user basis or something.

That said, that's something for later. I want to get the forums live first and foremost, since we can change things like this at a later point if needed and/or when we want to.

I figure we should close this issue, unless there is a reason to keep it open.

**Comment by Megalomaniak** [comment]
Yeah, that would be ideal I think.

**Comment by TwistedTwigleg** [comment]
Cool. In that case, I'll close this issue and make a new issue on the plugins repository.
