### ISSUE TITLE
Add Patreon integration to forum header

### ISSUE THREAD

**Issue by TwistedTwigleg** [TwistedTwigleg/vanilla-bootstrap#12]
Since we are trying to stay consistent with the theme and style in GodotEngine.org, we should probably add the the Patreon widget/button to the forum's header. That way the forum's header and GodotEngine.org's current header would be exactly the same.

@Megalomaniak found this link, which should provide a good starting point: [https://www.patreondevelopers.com/t/support-me-on-patreon-button/102/5](https://www.patreondevelopers.com/t/support-me-on-patreon-button/102/5)
and for reference [a wordpress plugin](https://wordpress.org/plugins/goal-tracker-for-patreon/).

That said, this should probably be tackled later, once the more pressing and prominent things are dealt with first.

- [ ] Add a simple styled button/link.
- [ ] Implement a plugin.
- [ ] Replace basic button/link.
- [ ] Further styling.

**Comment by Megalomaniak** [comment]
I'm thinking it's best to probably implement this as a smarty module, so as a vanilla plugin. Making a note here to myself that it's worth looking at the discord plugin that @TwistedTwigleg created for reference of basic pluginization and to remind myself to start googling for info on implementing smarty modules into vanilla.

**Comment by TwistedTwigleg** [comment]
Hopefully the Discord plugin helps.

It should show how to access metadata in a plugin module, which took me awhile to find out.

If you need to navigate the Vanilla source code, I would highly suggest searching for a keyword in all of the files within the vanilla install. That was how I found the comment in the source that lead me to eventually finding how to access the metadata.

I think the plugin also injects html into the iWidget, but I don’t remember right off.

Regardless, If there is any way I can help let me know!

**Comment by Megalomaniak** [comment]
Right, well.. since I consider it low priority I moved it to the future column in the project kanban. In other words I don't see it as a show blocker for the move, so I'm really in no hurry with this.

**Comment by Megalomaniak** [comment]
I've noticed that they have removed this from the engine website, probably because it was too much work to maintain and since they likely get most supporters through other means, like twitter for an example. So not sure if we should just close this?

I suspect we would have needed to ask someone with access to get the key for it to work anyways. And should that change, we would have needed to update it every time it changed, too. Seems like a potential maintenance nightmare TBH, cool as it would have been.

**Comment by TwistedTwigleg** [comment]
Interesting, I didn't notice they removed it. I wonder if it slowed down loading the website, kinda like how the Discord plugin slows down the forums when enabled. Regardless, I agree that making and maintaining a plugin for the Patreon widget would be hard to maintain, and if it was removed from the Godot site, then it probably means the widget didn't drive very much traffic.

While it might have been cool to add, I'm all for closing this issue.

**Comment by Megalomaniak** [comment]
Closing then, we can always reopen and re-investigate later.
