### ISSUE TITLE
The collapsible menus

### ISSUE THREAD

**Issue by Megalomaniak** [TwistedTwigleg/vanilla-bootstrap#14]
I'm not sure that every collapsible menu needs the "Hamburger" icon. Easy enough to set `display: none;` on them but then could remove the image tags from the master template just as well. Either ways it's not too pressing right now and there is plenty of time to discuss and think about that.

**Comment by TwistedTwigleg** [comment]
I'm totally fine with removing them.
I just added them because initially I just copied over the button from the header and made edits until it worked for collapsing the menus.

**Comment by Megalomaniak** [comment]
Since you have basically fixed this in your branch I'll close this.
