### ISSUE TITLE
Look into uploading forum images elsewhere

### ISSUE THREAD

**Issue by TwistedTwigleg** [TwistedTwigleg/vanilla-bootstrap#16]
The old Godot Developer forums used a Imgur plugin to handle image uploads, so the server hosting the forums wouldn't also host all of the images the forums uses. This reduces the file storage needed for the forums, with the caveat that these images had to be fetched from a different server.

However, as I mentioned in #13, I couldn't get the Imgur to work with the latest version of Vanilla, and even if the plugin was working, it would still need to be edited to work with the rich post editor.

This means that right now, any/all images uploaded to the forums will go straight to the server.

I doubt my server provider will have an issue for now, and supposedly I have 'unlimited' storage space, but potentially as the forums grow and more images are uploaded, they may have an issue with the amount of storage space the forums take.

That said, I doubt it will become an issue for quite awhile, or maybe it won't be an issue at all. If it becomes an issue, we can deal with it then, but I figure it is good to think ahead.

If anyone finds any alternatives, please post it here so we can look into it!

**Comment by Megalomaniak** [comment]
Can be closed for now and be reopened if and when necessary.
