### ISSUE TITLE
GodotDarkly - Remove white input boxes

### ISSUE THREAD

**Issue by TwistedTwigleg** [TwistedTwigleg/vanilla-bootstrap#25]
So I was making some edits to GodotDarkly and I realized we could change the color of the input boxes.

Right now they are white and it does provide nice contrast, but I wonder if it would be better to make the input boxes a darker color.

For example:

![Screenshot_2019-05-03 Imgur testing](https://user-images.githubusercontent.com/25082678/57151081-0c4acd80-6d9e-11e9-89af-ca9a07fd3504.png)

CSS:
~~~
// Make text areas gray with white text, just like how they will be when actually posted.
// (NOTE: Also effects the search bar.)
.InputBox
{
    background-color: @gray; //@gray-lighter;
    color: white;
}
~~~

_____

Personally I think it still maintains a nice contrast, albeit not quite as strong, and it looks more like what the end result will look like when posted. It also effects the search bar, for better or for worse, but if we wanted we could probably make it only effect the posting input boxes.
 
I like either way, but in my opinion the gray is a little easier on the eyes than the white.
Thoughts?

**Comment by Megalomaniak** [comment]
Works for me.

The search is an input field, so of course it should be consistent.

**Comment by TwistedTwigleg** [comment]
Cool, then I'll push the change! 👍 
Closing this issue...
