### ISSUE TITLE
github gist embeds

### ISSUE THREAD

**Issue by Megalomaniak** [TwistedTwigleg/vanilla-bootstrap#29]
One interesting idea I've been thinking of is maybe we could add gist embed to the forum.

just a few options I quickly looked up:

https://moebiusmania.github.io/gist-embed/
https://github.com/moebiusmania/gist-embed

https://github.blog/2008-07-24-embedded-gists/

**Comment by Megalomaniak** [comment]
This could be especially useful to our C# users, I think.

**Comment by TwistedTwigleg** [comment]
We might be able to add it to the Mediator plugin. I added GyfCat support and from what I remember it is a fairly straight forward process. Definitely something to look into!

**Comment by TwistedTwigleg** [comment]
Closed (at least for now) via [this PR](https://github.com/TwistedTwigleg/godot-forums-vanilla-plugins/pull/10) on the plugins repository.
