### ISSUE TITLE
Size of profile pictures for YAGA reactions

### ISSUE THREAD

**Issue by TwistedTwigleg** [TwistedTwigleg/vanilla-bootstrap#31]
As mentioned in [this thread](https://godotforums.org/discussion/20831/when-did-this-godot-forum-created#latest) on the Godot forums, the YAGA reaction icons make seeing the profile picture of the user who reacted difficult, especially for profile pictures with low contrast.

We could solve this by increasing the profile picture size slightly. For example:

![GodotForumsBiggerProfilePictureYAGAExample](https://user-images.githubusercontent.com/25082678/65469314-0af56c80-de35-11e9-994e-0b8d4931b3ed.png)

In the picture above, the profile pictures are scaled to `36` pixels, which might be just a *tad* large. We could easily scale it down to `32` or `28` while still maintaining better visibility. A downside with increasing the profile size is that the YAGA reactions will take up a bit more space, though most posts/topics don't get too many reactions so I think the change would be minimal for most posts.

**Comment by Megalomaniak** [comment]
Could also have them be enlarged on hover, and maybe only have the reaction type icon show on hover too. Just ideas to experiment with, not convinced they would necessarily work well, but only one way to know. 

Also in case there are too many reactions on a post, either the list could get truncated and only show up expanded with an absolute positioning(so they can show up outside the parent div bounds) on hover or just simply be truncated with perhaps a bit of text attached stating something like `+ n more` etc.

**Comment by TwistedTwigleg** [comment]
Yeah, I still need to test expanding on hover. I thought about making the icons invisible or semi-transparent until hover, but with how the HTML is setup I couldn't figure it out. To be fair, I only messed around with it for a little bit, so it is likely I missed something.

On the too many reactions case, I'm not sure what would be possible and/or easy to do just yet. I'm guessing that the easiest way to know would be to prototype and see what happens.
